export interface PublicEnv {
  enableQaLayers: boolean;
  mapStyle: string;
  pmtilesUrlPostWardsCandidateLabels?: string;
  pmtilesUrlPostWardsCandidate?: string;
  pmtilesUrlPreDistrictsCandidateLabels?: string;
  pmtilesUrlPreDistrictsCandidate?: string;
  pmtilesUrlPre?: string;
  pmtilesUrlPost?: string;
  pmtilesUrlIslands?: string;
  pmtilesUrlIslandsReef?: string;
  tileCacheBuster?: string;
  tileUrlIslands?: string;
  tileUrlIslandsFill?: string;
  tileUrlIslandsReef?: string;
  tileUrlPostWardsCandidateLabels?: string;
  tileUrlPostWardsCandidate?: string;
  tileUrlPost: string;
  tileUrlPreDistrictsCandidateLabels?: string;
  tileUrlPreDistrictsCandidate?: string;
  tileUrlPre: string;
}

// Self-hosted Protomaps "Heritage paper" basemap (Track A). Served from public/
// and generated by scripts/generate-basemap-style.mjs; assets live on R2.
const DEFAULT_MAP_STYLE = '/basemap-style.json';
type PublicEnvSource = Record<string, string | undefined>;

const browserPublicEnv: PublicEnvSource = {
  NEXT_PUBLIC_ENABLE_QA_LAYERS: process.env.NEXT_PUBLIC_ENABLE_QA_LAYERS,
  NEXT_PUBLIC_MAP_STYLE: process.env.NEXT_PUBLIC_MAP_STYLE,
  NEXT_PUBLIC_PMTILES_URL_POST_WARDS_CANDIDATE_LABELS:
    process.env.NEXT_PUBLIC_PMTILES_URL_POST_WARDS_CANDIDATE_LABELS,
  NEXT_PUBLIC_PMTILES_URL_POST_WARDS_CANDIDATE:
    process.env.NEXT_PUBLIC_PMTILES_URL_POST_WARDS_CANDIDATE,
  NEXT_PUBLIC_PMTILES_URL_PRE_DISTRICTS_CANDIDATE_LABELS:
    process.env.NEXT_PUBLIC_PMTILES_URL_PRE_DISTRICTS_CANDIDATE_LABELS,
  NEXT_PUBLIC_PMTILES_URL_PRE_DISTRICTS_CANDIDATE:
    process.env.NEXT_PUBLIC_PMTILES_URL_PRE_DISTRICTS_CANDIDATE,
  NEXT_PUBLIC_PMTILES_URL_PRE: process.env.NEXT_PUBLIC_PMTILES_URL_PRE,
  NEXT_PUBLIC_PMTILES_URL_POST: process.env.NEXT_PUBLIC_PMTILES_URL_POST,
  NEXT_PUBLIC_PMTILES_URL_ISLANDS: process.env.NEXT_PUBLIC_PMTILES_URL_ISLANDS,
  NEXT_PUBLIC_PMTILES_URL_ISLANDS_REEF: process.env.NEXT_PUBLIC_PMTILES_URL_ISLANDS_REEF,
  NEXT_PUBLIC_TILE_CACHE_BUSTER: process.env.NEXT_PUBLIC_TILE_CACHE_BUSTER,
  NEXT_PUBLIC_TILE_URL_ISLANDS: process.env.NEXT_PUBLIC_TILE_URL_ISLANDS,
  NEXT_PUBLIC_TILE_URL_ISLANDS_FILL: process.env.NEXT_PUBLIC_TILE_URL_ISLANDS_FILL,
  NEXT_PUBLIC_TILE_URL_ISLANDS_REEF: process.env.NEXT_PUBLIC_TILE_URL_ISLANDS_REEF,
  NEXT_PUBLIC_TILE_URL_POST_WARDS_CANDIDATE_LABELS:
    process.env.NEXT_PUBLIC_TILE_URL_POST_WARDS_CANDIDATE_LABELS,
  NEXT_PUBLIC_TILE_URL_POST_WARDS_CANDIDATE: process.env.NEXT_PUBLIC_TILE_URL_POST_WARDS_CANDIDATE,
  NEXT_PUBLIC_TILE_URL_PRE_DISTRICTS_CANDIDATE_LABELS:
    process.env.NEXT_PUBLIC_TILE_URL_PRE_DISTRICTS_CANDIDATE_LABELS,
  NEXT_PUBLIC_TILE_URL_PRE_DISTRICTS_CANDIDATE:
    process.env.NEXT_PUBLIC_TILE_URL_PRE_DISTRICTS_CANDIDATE,
  NEXT_PUBLIC_TILE_URL_POST: process.env.NEXT_PUBLIC_TILE_URL_POST,
  NEXT_PUBLIC_TILE_URL_PRE: process.env.NEXT_PUBLIC_TILE_URL_PRE,
};

function readRequiredEnv(env: PublicEnvSource, key: string): string {
  const value = env[key];

  if (!value) {
    throw new Error(`Missing required public environment variable: ${key}`);
  }

  return value;
}

function readBooleanEnv(env: PublicEnvSource, key: string): boolean {
  return env[key]?.trim().toLowerCase() === 'true';
}

export function readPublicEnv(env: PublicEnvSource = browserPublicEnv): PublicEnv {
  return {
    enableQaLayers: readBooleanEnv(env, 'NEXT_PUBLIC_ENABLE_QA_LAYERS'),
    mapStyle: env.NEXT_PUBLIC_MAP_STYLE || DEFAULT_MAP_STYLE,
    pmtilesUrlPostWardsCandidateLabels:
      env.NEXT_PUBLIC_PMTILES_URL_POST_WARDS_CANDIDATE_LABELS || undefined,
    pmtilesUrlPostWardsCandidate: env.NEXT_PUBLIC_PMTILES_URL_POST_WARDS_CANDIDATE || undefined,
    pmtilesUrlPreDistrictsCandidateLabels:
      env.NEXT_PUBLIC_PMTILES_URL_PRE_DISTRICTS_CANDIDATE_LABELS || undefined,
    pmtilesUrlPreDistrictsCandidate:
      env.NEXT_PUBLIC_PMTILES_URL_PRE_DISTRICTS_CANDIDATE || undefined,
    pmtilesUrlPre: env.NEXT_PUBLIC_PMTILES_URL_PRE || undefined,
    pmtilesUrlPost: env.NEXT_PUBLIC_PMTILES_URL_POST || undefined,
    pmtilesUrlIslands: env.NEXT_PUBLIC_PMTILES_URL_ISLANDS || undefined,
    pmtilesUrlIslandsReef: env.NEXT_PUBLIC_PMTILES_URL_ISLANDS_REEF || undefined,
    tileCacheBuster: env.NEXT_PUBLIC_TILE_CACHE_BUSTER || undefined,
    tileUrlIslands: env.NEXT_PUBLIC_TILE_URL_ISLANDS || undefined,
    tileUrlIslandsFill: env.NEXT_PUBLIC_TILE_URL_ISLANDS_FILL || undefined,
    tileUrlIslandsReef: env.NEXT_PUBLIC_TILE_URL_ISLANDS_REEF || undefined,
    tileUrlPostWardsCandidateLabels:
      env.NEXT_PUBLIC_TILE_URL_POST_WARDS_CANDIDATE_LABELS || undefined,
    tileUrlPostWardsCandidate: env.NEXT_PUBLIC_TILE_URL_POST_WARDS_CANDIDATE || undefined,
    tileUrlPost: readRequiredEnv(env, 'NEXT_PUBLIC_TILE_URL_POST'),
    tileUrlPreDistrictsCandidateLabels:
      env.NEXT_PUBLIC_TILE_URL_PRE_DISTRICTS_CANDIDATE_LABELS || undefined,
    tileUrlPreDistrictsCandidate: env.NEXT_PUBLIC_TILE_URL_PRE_DISTRICTS_CANDIDATE || undefined,
    tileUrlPre: readRequiredEnv(env, 'NEXT_PUBLIC_TILE_URL_PRE'),
  };
}

/**
 * Pick the basemap style file that matches the app's active locale so the
 * basemap's place labels stay consistent with the Viettrace boundary labels.
 *
 * The generator emits a Vietnamese style at the base name (e.g.
 * `/basemap-style.json`) and an English variant with a `-en` suffix
 * (`/basemap-style-en.json`). Vietnamese is the base file, so only `en` is
 * rewritten. External style URLs (e.g. the CARTO fallback) have no localized
 * variant and are returned unchanged.
 */
export function localizeBasemapStyle(style: string, locale: string): string {
  if (locale !== 'en') return style;
  // Only our self-hosted local style files have a `-en` sibling.
  if (style.startsWith('/') && style.endsWith('.json')) {
    return style.replace(/\.json$/, '-en.json');
  }
  return style;
}
